version: "3"

services:
  app:
    build: .
    container_name: simulator-service
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  default:
    name: external-example
    external: true
